[pytest]

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    --browser chromium
    --headed
    --html=reports/pytest-report.html
    --self-contained-html
    --capture=tee-sys

log_cli = true
log_cli_level = INFO

log_file = artifacts/logs/pytest_execution.log
log_file_level = INFO

log_cli_format = %(asctime)s | %(levelname)s | %(name)s | %(message)s
log_file_format = %(asctime)s | %(levelname)s | %(name)s | %(message)s

markers =
    order: control test execution