environment: vst_qa

application:
  base_url: "https://vstvfqa.vsttractors.com"
  landing_page: "/landing-page"

api:
  base_url: "https://vstvfusqa.vsttractors.com"
  login_endpoint: "/api/user/login/?isSSO=0"
  open_so_details_endpoint: "/api/mto/getOpenSODetailsData/"

browser:
  headless: false
  slow_mo: 0

timeouts:
  default: 10000
  navigation: 30000